# Generated by Django 2.2.7 on 2019-12-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='highlighted',
        ),
    ]
